name: Flutter CI with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # cần để SonarCloud phân tích chính xác

      # 2. Setup Java (SonarCloud cần Java để chạy scanner)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # đổi theo version bạn đang dùng

      # 4. Build & Test Flutter (thay cho <commands_to_build_your_project>)
      - name: Analyze Flutter
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      # 5. SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # token mặc định của GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # bạn phải tạo trên SonarCloud